#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.6.8 on Sun Mar 29 12:26:32 2015
#
import sys, wx, os 
from rmss_dates import *
import ConfigParser
import time
import datetime
import wx.lib.agw.pybusyinfo as PBI
import images
import subprocess


DB_HOST = config.HOST #'localhost'
DB_USER = config.USER #'root'
DB_USER_PASSWORD = config.PASS #'pass'
#DB_NAME = '/backup/dbnames.txt'
DB_NAME = config.MYDB #'rms2'

def data_restore(self):
    mydlg = wx.DirDialog(self, "Choose a Directory:",style=wx.DD_DEFAULT_STYLE
                           #| wx.DD_DIR_MUST_EXIST
                           #| wx.DD_CHANGE_DIR
                                   )
            #newPath = rmss_config.BACKUP_PATH
            #mydlg.SetPath(newPath)
    
    if mydlg.ShowModal() == wx.ID_OK:
        RESTORE_PATH = mydlg.GetPath()
        
        message = "Please Wait FEW Seconds, \n While DATABASE is RESTORING \n I'm Working..."
        busy = PBI.PyBusyInfo(message, parent=None, title="Reatoring Database",
                              icon=images.Smiles.GetBitmap())
        #tdb = 'rms2' # DATA BASE IN WHICH ANOTHER DATA TO BE RESTORE
        db = DB_NAME
        dumpcmd = "C:/MySQL_Py/mysql -u " + DB_USER + " -p" + DB_USER_PASSWORD + " " + db + " < " + RESTORE_PATH + "/" + db + ".sql" # FOR LINUX UBUNTU / FOR WINDOWS 7
        #os.system(dumpcmd)
        dc=subprocess.Popen(dumpcmd,shell=True)
        dc.wait()
        wx.Yield()
                 
        for indx in xrange(1):
            wx.MilliSleep(1000)
        del busy
        
        wx.MessageBox("RESTORE SUCCESSFULLY COMPLETED  !! ",
                      "Great ! Y ",wx.ICON_INFORMATION)
        return
        

